/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Track = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'coverEmoji' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'downloadUrl' : IDL.Text,
  'likes' : IDL.Nat,
  'genre' : IDL.Text,
  'artist' : IDL.Text,
  'plays' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllTracks' : IDL.Func([], [IDL.Vec(Track)], ['query']),
  'getFeaturedTracks' : IDL.Func([IDL.Nat], [IDL.Vec(Track)], ['query']),
  'getTrack' : IDL.Func([IDL.Nat], [Track], ['query']),
  'getTracksByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Track)], ['query']),
  'incrementPlayCount' : IDL.Func([IDL.Nat], [], []),
  'searchTracks' : IDL.Func([IDL.Text], [IDL.Vec(Track)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Track = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'coverEmoji' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'downloadUrl' : IDL.Text,
    'likes' : IDL.Nat,
    'genre' : IDL.Text,
    'artist' : IDL.Text,
    'plays' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllTracks' : IDL.Func([], [IDL.Vec(Track)], ['query']),
    'getFeaturedTracks' : IDL.Func([IDL.Nat], [IDL.Vec(Track)], ['query']),
    'getTrack' : IDL.Func([IDL.Nat], [Track], ['query']),
    'getTracksByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Track)], ['query']),
    'incrementPlayCount' : IDL.Func([IDL.Nat], [], []),
    'searchTracks' : IDL.Func([IDL.Text], [IDL.Vec(Track)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };