/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Track {
  'id' : bigint,
  'title' : string,
  'duration' : string,
  'coverEmoji' : string,
  'tags' : Array<string>,
  'year' : bigint,
  'description' : string,
  'downloadUrl' : string,
  'likes' : bigint,
  'genre' : string,
  'artist' : string,
  'plays' : bigint,
}
export interface _SERVICE {
  'getAllTracks' : ActorMethod<[], Array<Track>>,
  'getFeaturedTracks' : ActorMethod<[bigint], Array<Track>>,
  'getTrack' : ActorMethod<[bigint], Track>,
  'getTracksByGenre' : ActorMethod<[string], Array<Track>>,
  'incrementPlayCount' : ActorMethod<[bigint], undefined>,
  'searchTracks' : ActorMethod<[string], Array<Track>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];